const mappingDict = {
    "bay of bengal": "Bangladesh",
    "british virgin islands": "United Kingdom",
    "french polynesia": "France",
    "guam": "United States of America",
    "okinawa": "Japan",
    "netherlands antilles": "Netherlands",
    "falkland islands": "Falkland Is.",
    "palestinian territories": "Palestine",
    "equatorial guinea / cameroon": "Eq. Guinea",
    "scotland": "United Kingdom",
    "johnston island": "United States of America",
    "british west indies": "United Kingdom",
    "balkans": "Greece",  
    "san domingo": "Dominican Rep.",
    "dominican republic": "Dominican Rep.",
    "american samoa": "United States of America",
    "new britain": "Papua New Guinea",
    "korea": "South Korea",
    "british new guinea": "Papua New Guinea",
    "crete": "Madagascar",
    "gulf of aden": "Yemen",
    "coast of africa": "Côte d'Ivoire", 
    "new guinea": "Papua New Guinea", 
    "admiralty islands": "Papua New Guinea",
    "columbia": "Colombia",
    "azores": "Portugal",
    "solomon islands": "Solomon Is.",
    "martinique": "France",
    "british isles": "United Kingdom",
    "persian gulf": "Iran",
    "trinidad & tobago": "Trinidad and Tobago",
    "burma": "Myanmar",
    "st. martin": "France",
    "java": "Indonesia",
    "hong kong": "China",
    "reunion": " Madagascar",
    "antigua": "Puerto Rico",
    "monaco": "France",
    "tuvalu": "Fiji",
    "western samoa": "Fiji",
    "cape verde": "Senegal",
    "seychelles": "Madagascar",
    "barbados": "Venezuela",
    "marshall islands": "Solomon Is.",
    "northern mariana islands": "Papua New Guinea",
    "central pacific": "United States of America",
    "cayman islands": "Cuba",
    "turks & caicos": "Dominican Rep.",
    "nevis": "Puerto Rico",
    "malta": "Italy",
    "cook islands": "Fiji",
    "kiribati": "Fiji",
    "federated states of micronesia": "Fiji",
    "palau": "Papua New Guinea",
    "micronesia": "Papua New Guinea",
    "singapore": "Malaysia",
    "grenada": "Venezuela",
    "aruba": "Venezuela",
    "diego garcia": "Sri Lanka",
    "bahrain": "Qatar",
    "tonga": "Fiji",
    "grand cayman": "Cuba",
    "curacao": "Venezuela",
    "mayotte": "Madagascar",
    "maldive islands": "Madagascar",
    "samoa": "Fiji",
    "bermuda": "Bahamas",
    "mauritius": "Madagascar", 
};

export {mappingDict};